### ISSUE TITLE
move Quandel data source to seperate assembly

### ISSUE THREAD

**Issue by leo90skk** [leo90skk/qdms#23]

**Comment by leo90skk** [comment]
I did the work in branch issue-23

One thing that should be verified:
I removed the use of Application.Current.Dispatcher.Invoke when the data source writes to the log. I don't know if that will cause some UI problems. If that is the case, we should move that part to the QDMSServer project and not into the new assembly (preparing for #18).

**Comment by qusma** [comment]
If I remember correctly the use of the Dispatcher was because writing to the log from a different thread could cause trouble with the log listbox and crash the application. Probably a better solution is to use ConcurrentNotifierBlockingList instead of ObservableCollection for the LogMessages collection in MainWindow? Needs to be tested.

**Comment by qusma** [comment]
OK so this can be merged into master. I was right about the ocllection

**Comment by leo90skk** [comment]
merged to master, isse closed
