### ISSUE TITLE
Forex Calendar data source

### ISSUE THREAD

**Issue by leo90skk** [leo90skk/qdms#3]
add a new data service that can provide economic release dates that influence other financial instruments f.e. foreign exchange.

Sample websites that are providing similar data via websites:
* https://www.dailyfx.com/calendar
* http://www.fxstreet.com/economic-calendar
* http://www.forexfactory.com/calendar.php

**Comment by leo90skk** [comment]
Possible apis that could be used:
https://github.com/xuyuwei/Forex-Calendar-API
https://github.com/jinahadam/fiscal

**Comment by qusma** [comment]
Should we store this stuff locally or just re-download it whenever it's requested?

**Comment by leo90skk** [comment]
I think at least - in the long run - we should store it. When you wanna do some backtesting f.e. to create your own forex EA, you will need the data right away to get the best backtesting performance.

Actually I don't know when I will implement it. It's today just an idea. I wanna focus now to get version 1.0 to RTM. When someone else can take over, its ok for me.

It has something similar with #11:
* this issue is focused for the forex market
* issue #11 is focused for the stock market

**Comment by qusma** [comment]
I took a swing at it, take a look at the data structure & broker here: bb862784600db257a4c55414c4e46ac30e5f6098

Also added a client for FXStreet: fc789e5dcf12725c9e64a8eb2b37a7f571e64f66 (trying my hand at F#, pretty fun)

Some questions: does it make sense for the broker to use multiple different sources (i.e. FXStreet and forexfactory) at the same time? I think it could lead to a lot of duplication, since they probably just have the same data, right? So I was thinking that it might be better if the user would pick one source and only that one would be used for all requests.

I haven't done anything on the networking side, this seems like the sort of thing that we'd send over HTTP rather than zmq. So it's best to wait for that.

Also: add a calendar to the UI to display this stuff?

**Comment by leo90skk** [comment]
Tour swing look at the beginning good. I would prefer to usw ISO Codes for Country (2 chars) and Currency (3 chars).

Your client looks nice. I Mike the idea to use F# - you can express mathematic logic easier as with C#. I think we should discuss a style guide for "when using F# and when using C#". I would prefer it in indicator and trading signal calculation Both will be dotNet Core compatible ... without a style guide we could end up in spaghetti code...

Yes, it might make sense to get forex data from different sources. As I know, the prices are created by the brokers in some way, and there are not all the same. Stocks work not equaly here, i think. Look here for example: https://www.mql5.com/en/signals/165324
This is a public trading signal from a user that can be cloned... In the tab " Slipperage" you can see that different brokers have pipe differences.

Personally I don't think we need it in the server UI. Would be nice but not necessary. Actually every user I guess would use the client api at the end ... maybe for a backtesting scenario with forex.

**Comment by leo90skk** [comment]
I merged the pull request and close this issue.
